Repository aemsites/volvotrucks-na, pull requests merged in 2024-12, with the labels that each got.

#132 Footer links alignement issue #36
  blocks/footer/footer.css
Labels: Bug

#138 Release 26
  blocks/footer/footer.css
  blocks/key-facts/key-facts.css
  blocks/v2-article-search/v2-article-search.css
  blocks/v2-article-search/v2-article-search.js
  blocks/v2-key-facts/v2-key-facts.css
  blocks/v2-key-facts/v2-key-facts.js
  package-lock.json
  package.json
  templates/v2-magazine/v2-magazine.js
Labels: Ignore for release

#144 Fix hero with youtube video link #143
  common/modal/modal.js
Labels: bugfix

#152 V2 Video on Mobile #133
  blocks/v2-video/v2-video.js
Labels: bugfix

#148 Connect GraphQL to magazine related blocks #136
  blocks/magazine-articles/magazine-articles.js
  blocks/related-articles/related-articles.js
  blocks/search/autosuggest.js
  blocks/search/search.js
  blocks/v2-article-cards/v2-article-cards.js
  blocks/v2-article-search/v2-article-search.js
  blocks/v2-stories-carousel/v2-stories-carousel.js
  scripts/search-api.js
  scripts/services/magazine.service.js
Labels: FR

#156 Release 27
  blocks/dealer-locator/dealer-locator.css
  blocks/dealer-locator/sidebar-maps.js
  blocks/eloqua-form/forms/ContactUsVolvo.html
  blocks/eloqua-form/forms/ExceedingExpectationsSignup.html
  blocks/eloqua-form/forms/VNR_Electric_CU.html
  blocks/eloqua-form/forms/copyOfTruck19Q3EMTeaserSignUpFR-1582126715298.html
  blocks/eloqua-form/forms/copyfuelefficient-637860630969151756.html
  blocks/eloqua-form/forms/event-from.html
  blocks/eloqua-form/forms/servicesubscriptions.html
  blocks/eloqua-form/forms/turbo-calculator-form.html
  blocks/magazine-articles/magazine-articles.js
  blocks/related-articles/related-articles.js
  blocks/search/autosuggest.js
  blocks/search/search.js
  blocks/v2-article-cards/v2-article-cards.js
  blocks/v2-article-search/v2-article-search.js
  blocks/v2-stories-carousel/v2-stories-carousel.js
  blocks/v2-video/v2-video.js
  package-lock.json
  package.json
  scripts/search-api.js
  scripts/services/magazine.service.js
  styles/styles.css
  tools/tagger/tagger.css
Labels: Ignore for release

#154 add import Noto font to the head & minor font adjustments #153
  head.html
  styles/styles.css
Labels: bugfix

#162 Applications Module (1 of 2) #111
  blocks/v2-applications-carousel/v2-applications-carousel.css
  blocks/v2-applications-carousel/v2-applications-carousel.js
  scripts/common.js
Labels: FR

#165 add a z-index for all viewports #160
  blocks/v2-article-search/v2-article-search.css
Labels: bugfix
