Repository aemsites/volvotrucks-na, pull requests merged in 2024-11, with the labels that each got.

#113 Library link changes #109
  .github/pull_request_template.md
  tools/sidekick/config.json
  tools/sidekick/library.html
Labels: NFR

#115 Cleanup configs #105
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/new_feature.yml
  .github/ISSUE_TEMPLATE/technical-debt.yml
  blocks/v2-truck-lineup/v2-truck-lineup.js
  scripts/common.js
  tools/fgrep-attr/fgrep.js
Labels: NFR

#118 Release 25
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/new_feature.yml
  .github/ISSUE_TEMPLATE/technical-debt.yml
  .github/pull_request_template.md
  blocks/header/header.css
  blocks/header/header.js
  blocks/magazine-articles/magazine-articles.js
  blocks/search/autosuggest.js
  blocks/search/search.js
  blocks/search/templates.js
  blocks/v2-article-search/v2-article-search.css
  blocks/v2-article-search/v2-article-search.js
  blocks/v2-truck-lineup/v2-truck-lineup.js
  constants.json
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  scripts/magazine-press.js
  scripts/search-api.js
  styles/styles.css
  tools/fgrep-attr/fgrep.js
  tools/sidekick/config.json
  tools/sidekick/library.html
Labels: Ignore for release

#127 V2 Key Facts block #12
  blocks/key-facts/key-facts.css
  blocks/v2-key-facts/v2-key-facts.css
  blocks/v2-key-facts/v2-key-facts.js
Labels: FR

#130 v2-article-search is added automatically based on metadata #122
  blocks/v2-article-search/v2-article-search.css
  blocks/v2-article-search/v2-article-search.js
  templates/v2-magazine/v2-magazine.js
Labels: bugfix
