Repository aemsites/volvotrucks-na, pull requests merged in 2024-10, with the labels that each got.

#8 749 - handle index names in gh action client_payload.path
  .github/workflows/publish-notifier.yaml
  .github/workflows/unpublish-notifier.yaml
Labels: searcheng

#10 Controls and sound configuration added to video #9
  scripts/video-helper.js
Labels: bug

#16 Revert change #797
  head.html
Labels: bugfix
