Repository aemsites/volvotrucks-na, pull requests merged in 2025-02, with the labels that each got.

#226 V2 media w/ text block formatting and spacing is incorrect #205
  blocks/v2-media-with-text/v2-media-with-text.css
Labels: bugfix

#223 V2 Content Carousel - Adjustment to text displayed below images #218
  blocks/v2-content-carousel/v2-content-carousel.css
  blocks/v2-content-carousel/v2-content-carousel.js
Labels: FR

#227 [V2 Media with Text] - Option to change title text size #211
  blocks/v2-media-with-text/v2-media-with-text.css
  blocks/v2-media-with-text/v2-media-with-text.js
Labels: FR

#228 FR: V2 Text - Option to change text title to a smaller size #212
  blocks/v2-text/v2-text.css
  blocks/v2-text/v2-text.js
Labels: FR

#224 NFR: 404 Page Localization - Primary Markets Volvo #59
  404.html
  blocks/fragment/fragment.js
Labels: NFR

#238 Release 30
  404.html
  blocks/dealer-locator/sidebar-maps.js
  blocks/fragment/fragment.js
  blocks/v2-applications-carousel/v2-applications-carousel.css
  blocks/v2-applications-carousel/v2-applications-carousel.js
  blocks/v2-content-carousel/v2-content-carousel.css
  blocks/v2-content-carousel/v2-content-carousel.js
  blocks/v2-forms/forms/event-notify.js
  blocks/v2-media-with-text/v2-media-with-text.css
  blocks/v2-media-with-text/v2-media-with-text.js
  blocks/v2-text/v2-text.css
  blocks/v2-text/v2-text.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  common/sidebar/sidebar.css
  constants.json
  icons/check-thin.svg
  package-lock.json
  package.json
  placeholder.json
  scripts/delayed.js
  styles/styles.css
Labels: Ignore for release

#229 FR: V2 dealer locator teaser - Layout enhancement #217
  blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.css
  blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.js
Labels: FR

#239 Fav icon not appearing on BING search #151
  head.html
  styles/apple-touch-icon.png
  styles/favicon-192x192.png
  styles/favicon-64x64.png
Labels: bugfix

#247 Release 31
  blocks/engine-specifications/engine-specifications.css
  blocks/engine-specifications/engine-specifications.js
  blocks/engine-specifications/performance-chart.js
  blocks/pardot-form/pardot-form.js
  blocks/v2-custom-form/responses/error.js
  blocks/v2-custom-form/responses/success.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.css
  blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.js
  blocks/v2-forms/forms/event-notify.js
  common/custom-dropdown/custom-dropdown.js
  eslint.config.mjs
  package-lock.json
  package.json
  placeholder.json
  scripts/scripts.js
Labels: Ignore for release
