Repository aemsites/volvotrucks-na, pull requests merged in 2025-06, with the labels that each got.

#377 Spike: Update GitHub Actions - Notifications (2 of 4) #89
  .github/workflows/publish-notifier.yaml
Labels: Spike

#381 updates old connector to test email on error
  .github/workflows/old-publish-notifier.yaml
Labels: Ignore for release

#374 FR: Inconsistency in search suggestions #166
  blocks/search/autosuggest.js
  blocks/search/templates.js
  scripts/search-api.js
Labels: FR

#393 363 - Update favicon files
  favicon.ico
  head.html
  styles/apple-touch-icon.png
  styles/favicon-192x192.png
  styles/favicon-32x32.png
  styles/favicon-64x64.png
  styles/favicon.svg
Labels: bugfix

#392 FR: Adapting Press Releases to Use Pagination from Article Cards
  blocks/press-releases/press-releases.js
  common/pagination/pagination.css
Labels: FR

#391 FR: Remove Volvotrucks Search Old Resources #361
  .github/workflows/old-publish-notifier.yaml
  .github/workflows/old-unpublish-notifier.yaml
Labels: FR
