Repository aemsites/volvotrucks-na, pull requests merged in 2025-09, with the labels that each got.

#482 FR: New variant for the V2 Content Card block #470
  blocks/v2-content-card/v2-content-card.css
  blocks/v2-content-card/v2-content-card.js
Labels: FR

#479 FR: New variant for the V2 Content Carousel block #468
  blocks/v2-content-carousel/v2-content-carousel.css
  blocks/v2-content-carousel/v2-content-carousel.js
  scripts/common.js
  styles/styles.css
Labels: FR

#483 FR: Update V2 Truck Lineup block #473
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
Labels: FR

#501 Release 44
  blocks/v2-content-card/v2-content-card.css
  blocks/v2-content-card/v2-content-card.js
  blocks/v2-content-carousel/v2-content-carousel.css
  blocks/v2-content-carousel/v2-content-carousel.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-inpage-navigation/v2-inpage-navigation.css
  blocks/v2-inpage-navigation/v2-inpage-navigation.js
  blocks/v2-key-facts/v2-key-facts.css
  blocks/v2-key-facts/v2-key-facts.js
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
  common/custom-dropdown/custom-dropdown.js
  package-lock.json
  package.json
  scripts/common.js
  scripts/scripts.js
  styles/styles.css
Labels: Ignore for release

#508 Bug: Large text size for Content Carousel #507
  blocks/v2-content-carousel/v2-content-carousel.css
Labels: bugfix

#512 BUG: The selected article is also displayed in "Related stories" carousel #464
  blocks/v2-stories-carousel/v2-stories-carousel.js
  scripts/common.js
Labels: bugfix

#511 Transport Canada: Add "Precautions to Minimize Risk“ [Volvo-English] #497
  blocks/vin-number/vin-number.js
  placeholder.json
Labels: FR

#515 Transport Canada: Add "Remedy Availability“ [Volvo-English] #498
  blocks/vin-number/vin-number.js
  placeholder.json
Labels: FR

#518 Transport Canada: Add "Transport Canada Issue Date“ [Volvo-English] #496
  blocks/vin-number/vin-number.js
  placeholder.json
Labels: FR

#520 Transport Canada: Rename "Issue Date" to "NHTSA Issue Date“ [Volvo-English] #493
  placeholder.json
Labels: FR
