Repository aemsites/volvotrucks-na, pull requests merged in 2025-07, with the labels that each got.

#404 Bug: V2 Media with Text - Ensure consistent play/pause/mute button styling and correct video aspect ratio. #204
  blocks/v2-media-with-text/v2-media-with-text.css
Labels: bugfix

#409 Spike: Investigate High Volume of "Direct" Traffic in GA for Volvo Trucks Website #401
  scripts/delayed.js
Labels: Spike

#412 FR: Update GitHub Actions - Notifications (3 of 4) #190
  .github/workflows/old-publish-notifier.yaml
Labels: FR

#414 FR: Update GitHub Actions - Notifications (3 of 4) #190
  .github/workflows/old-publish-notifier.yaml
  .github/workflows/publish-notifier.yaml
Labels: FR

#417 Bug: V2 Media with text - Video [AEM assets link] is not working #375
  blocks/v2-media-with-text/v2-media-with-text.js
  scripts/common.js
Labels: bugfix

#416 NFR: Improve font loading strategy #62
  blocks/dealer-locator/sidebar-maps.js
  fonts/VolvoBroadProDigital-basic.woff
  fonts/VolvoBroadProDigital-basic.woff2
  fonts/VolvoBroadProDigital-extended.woff
  fonts/VolvoBroadProDigital-extended.woff2
  fonts/VolvoBroadProDigital.woff2
  fonts/VolvoNovum-Medium-basic.woff
  fonts/VolvoNovum-Medium-basic.woff2
  fonts/VolvoNovum-Medium-extended.woff
  fonts/VolvoNovum-Medium-extended.woff2
  fonts/VolvoNovum-Medium.woff
  fonts/VolvoNovum-Medium.woff2
  fonts/VolvoNovum-Regular-basic.woff
  fonts/VolvoNovum-Regular-basic.woff2
  fonts/VolvoNovum-Regular-extended.woff
  fonts/VolvoNovum-Regular-extended.woff2
  fonts/VolvoNovum-Regular.woff2
  fonts/volvobroadprodigital.woff
  fonts/volvonovum-regular.woff
  head.html
  scripts/font-loader.js
  scripts/scripts.js
  styles/lazy-styles.css
  styles/styles.css
Labels: NFR

#424 Bug: Font size from "Safety" section
  common/modal/modal.css
Labels: bugfix

#426 FR: Autocomplete Magazine Search
  blocks/search/autosuggest.js
  blocks/v2-article-search/v2-article-search.css
  blocks/v2-article-search/v2-article-search.js
  placeholder.json
Labels: FR

#425 NFR: FE WORK - implement press releases from query to opensearch #389
  blocks/magazine-articles/magazine-articles.js
  blocks/press-releases/press-releases.css
  blocks/press-releases/press-releases.js
  placeholder.json
  scripts/search-api.js
  scripts/services/press-release.service.js
Labels: NFR

#434 Release 41
  blocks/magazine-articles/magazine-articles.js
  blocks/press-releases/press-releases.css
  blocks/press-releases/press-releases.js
  blocks/search/autosuggest.js
  blocks/v2-article-search/v2-article-search.css
  blocks/v2-article-search/v2-article-search.js
  blocks/v2-custom-form/v2-custom-form.js
  common/modal/modal.css
  package-lock.json
  package.json
  placeholder.json
  scripts/search-api.js
  scripts/services/press-release.service.js
Labels: Ignore for release

#441 Bug: Font color Bugs from "Safety" section
  blocks/v2-media-with-text/v2-media-with-text.css
Labels: bugfix
