Repository aemsites/volvotrucks-na, pull requests merged in 2025-08, with the labels that each got.

#443 Bug: MyTruck App Padding from Connectivity section
  common/modal/modal.css
Labels: bugfix

#439 CR: Remove inscription from product specs
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
Labels: CR

#442 Bug: Web version of the Dealer Locator shows incorrect distance #418
  blocks/dealer-locator/sidebar-maps.js
Labels: bugfix

#444 CR: Adjust padding on the PDP section
  blocks/v2-masonry-grid/v2-masonry-grid.css
  blocks/v2-section-header/v2-section-header.css
Labels: CR

#456 FR: Restrict Resource Publishing and Update Path Handling in publish-notifier.yaml #431
  .github/workflows/unpublish-notifier.yaml
Labels: FR

#454 FR: Extend limit of articles in magazine query #438
  blocks/magazine-articles/magazine-articles.css
  blocks/magazine-articles/magazine-articles.js
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
  scripts/magazine-press.js
  scripts/services/magazine.service.js
Labels: FR

#460 Bug: Delay in loading of header on homepage #452
  scripts/common.js
  scripts/scripts.js
Labels: bugfix

#466 FR: Implement dynamic pagination for press releases and magazine articles #437
  blocks/press-releases/press-releases.js
  blocks/v2-article-cards/v2-article-cards.js
  common/pagination/pagination.js
Labels: FR
