Repository aemsites/volvotrucks-na, pull requests merged in 2025-03, with the labels that each got.

#246 FR: Restream integration (embed web player) #197
  blocks/v2-hero-reveal/v2-hero-reveal.css
  blocks/v2-hero-reveal/v2-hero-reveal.js
  blocks/v2-hero/v2-hero.js
  blocks/v2-livestream-embed/v2-livestream-embed.js
  blocks/v2-video/v2-video.js
  common/modal/modal.css
  common/modal/modal.js
  scripts/video-helper.js
Labels: FR

#264 FR: Update style for the chart engine ratings #251
  blocks/engine-specifications/engine-specifications.css
  constants.json
Labels: FR

#267 Release 32
  blocks/engine-specifications/engine-specifications.css
  blocks/v2-forms/v2-forms.js
  constants.json
  package-lock.json
  package.json
  templates/v2-magazine/v2-magazine.js
Labels: Ignore for release

#270 Stories on Volvo Trucks CA are not loading on Home page #250
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
Labels: bugfix

#271 FR: Adjust performance specifications chart for the engine ratings (2 of 3) #241
  blocks/engine-specifications/engine-specifications.css
  blocks/engine-specifications/engine-specifications.js
  blocks/engine-specifications/performance-chart.js
  placeholder.json
Labels: FR
