Repository aemsites/volvotrucks-na, pull requests merged in 2025-04, with the labels that each got.

#291 FR: Form Layout for MCAE - VT #230
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  styles/styles.css
Labels: FR

#311 Custom playback button not working on iOS #310 Open
  scripts/video-helper.js
Labels: bugfix

#308 Glitchy interaction on page navigation for VNR PDP #275
  blocks/v2-inpage-navigation/v2-inpage-navigation.js
  scripts/scripts.js
Labels: bugfix

#300 FR: Enable article filter to update magazine page #294 #295
  blocks/v2-article-cards/v2-article-cards.css
  blocks/v2-article-cards/v2-article-cards.js
  blocks/v2-article-search/v2-article-search.js
  constants.json
  scripts/search-api.js
  scripts/services/magazine.service.js
Labels: FR

#302 Enable AEM asset video links in video blocks #280
  blocks/v2-banner/v2-banner.css
  blocks/v2-banner/v2-banner.js
  blocks/v2-content-card/v2-content-card.css
  blocks/v2-content-card/v2-content-card.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
  blocks/v2-key-facts/v2-key-facts.css
  blocks/v2-masonry-grid/v2-masonry-grid.css
  blocks/v2-masonry-grid/v2-masonry-grid.js
  blocks/v2-media-with-text/v2-media-with-text.css
  blocks/v2-media-with-text/v2-media-with-text.js
  common/modal/modal.js
  scripts/videojs/video-js.min.css
Labels: FR

#313 FR: Double Column Variant Form for the MCAE - VT #283
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#318 Bug: Wrong placement of the video pause button across VT on mobile #274
  blocks/v2-media-with-text/v2-media-with-text.css
  styles/styles.css
Labels: bugfix, Bug

#317 NFR: Update Codebase with Latest Changes from AEM Boilerplate #185
  .github/workflows/run-tests.yaml
  .gitignore
  blocks/fragment/fragment.js
  blocks/get-an-offer/get-an-offer.js
  blocks/tabbed-accordion/tabbed-accordion.js
  blocks/v2-hero-reveal/v2-hero-reveal.js
  common/modal/modal.js
  package-lock.json
  package.json
  scripts/aem.js
  scripts/common.js
  scripts/scripts.js
  styles/header-font.css
  styles/styles.css
  test/blocks/hero/hero.test.js
  test/scripts/block-utils.test.js
  test/scripts/body.html
  test/scripts/common.test.js
  test/scripts/config.html
  test/scripts/dummy.html
  test/scripts/head.html
  test/scripts/media_mock.png
  test/scripts/scripts.test.js
  test/scripts/types.d.ts
  test/scripts/video-helper.test.js
Labels: NFR
