Repository aemsites/volvotrucks-na, pull requests merged in 2025-05, with the labels that each got.

#332 Spike: Improve the loading of AEM asset videos and the Video.js library #306
  scripts/delayed.js
  scripts/scripts.js
  scripts/video-helper.js
Labels: Spike

#344 FR: [VTNA] Centering the V2 Custom Form content #320
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#345 FR: MCAE form fields validations - VT #327
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#346 NFR: Language setting needs to be applied to all website - VT #169
  scripts/scripts.js
Labels: NFR

#347 FR: Add honeypot field to V2 Custom Form block detect bot submission #312
  blocks/v2-custom-form/v2-custom-form.js
  styles/styles.css
Labels: FR

#349 NFR: FE language query standarization #149
  blocks/search/autosuggest.js
  scripts/search-api.js
Labels: NFR

#352 Release 36
  blocks/search/autosuggest.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/modal/modal.js
  package-lock.json
  package.json
  scripts/common.js
  scripts/scripts.js
  scripts/search-api.js
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release

#355 CR: Update V2 Stories Carousel block filtering logic #330
  blocks/v2-stories-carousel/v2-stories-carousel.js
  scripts/services/magazine.service.js
Labels: CR
