Repository aemsites/volvotrucks-na, pull requests merged in 2025-01, with the labels that each got.

#167 Bug: Blurry Images on Volvo Trucks Stories Overview Page #159
  blocks/v2-article-cards/v2-article-cards.js
Labels: bugfix

#163 add failsafe to constants #135
  blocks/header/header.js
  blocks/search/autosuggest.js
  blocks/search/search.js
  blocks/v2-article-search/v2-article-search.js
  scripts/common.js
  scripts/delayed.js
  scripts/scripts.js
  scripts/search-api.js
  scripts/services/magazine.service.js
  scripts/validate-countries.js
  scripts/validate-elements.js
Labels: NFR

#173 Dynamic truck lineup #123
  blocks/v2-dynamic-truck-lineup/v2-dynamic-truck-lineup.css
  blocks/v2-dynamic-truck-lineup/v2-dynamic-truck-lineup.js
  blocks/v2-truck-lineup/v2-truck-lineup.css
  blocks/v2-truck-lineup/v2-truck-lineup.js
Labels: FR

#182 V2 Media with Text - Video with Poster #29
  blocks/v2-media-with-text/v2-media-with-text.css
  blocks/v2-media-with-text/v2-media-with-text.js
  scripts/video-helper.js
  styles/styles.css
Labels: bugfix

#187 NFR: Pixel Tracking Code #177
  constants.json
  scripts/delayed.js
Labels: NFR

#195 Volvo Trucks NA Javascript errors #107
  404.html
  blocks/dealer-locator/sidebar-maps.js
  blocks/get-an-offer/get-an-offer.js
  blocks/key-facts/key-facts.js
  blocks/v2-forms/v2-forms.js
  scripts/aem.js
  scripts/scripts.js
  scripts/video-helper.js
Labels: bugfix

#202 Release 29
  404.html
  blocks/dealer-locator/sidebar-maps.js
  blocks/get-an-offer/get-an-offer.js
  blocks/key-facts/key-facts.js
  blocks/v2-forms/v2-forms.js
  blocks/v2-media-with-text/v2-media-with-text.css
  blocks/v2-media-with-text/v2-media-with-text.js
  constants.json
  package-lock.json
  package.json
  scripts/aem.js
  scripts/delayed.js
  scripts/scripts.js
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release

#203 Fav icon not appearing on BING search #151
  head.html
  scripts/common.js
Labels: bugfix
